# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/Joe Harris/Documents/Embedded Systems Cert/Logic Analysis_Design using Verilog/Redo Assignement/Transmitter_sim/Transmitter_sim.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Joe Harris/Documents/Embedded Systems Cert/Logic Analysis_Design using Verilog/Redo Assignement/Transmitter_sim/Transmitter_sim.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  {C:/Users/Joe Harris/Documents/Embedded Systems Cert/Logic Analysis_Design using Verilog/Redo Assignement/Transmitter_sim/Transmitter_sim.srcs/sources_1/imports/new/transmitter.v}
  {C:/Users/Joe Harris/Documents/Embedded Systems Cert/Logic Analysis_Design using Verilog/Redo Assignement/Transmitter_sim/Transmitter_sim.srcs/sources_1/imports/new/transmit_debouncing.v}
  {C:/Users/Joe Harris/Documents/Embedded Systems Cert/Logic Analysis_Design using Verilog/Redo Assignement/Transmitter_sim/Transmitter_sim.srcs/sources_1/imports/new/top.v}
}
read_xdc {{C:/Users/Joe Harris/Documents/Embedded Systems Cert/Logic Analysis_Design using Verilog/Redo Assignement/Transmitter_sim/Transmitter_sim.srcs/constrs_1/imports/UART serial communication/Basys3_Master.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/Joe Harris/Documents/Embedded Systems Cert/Logic Analysis_Design using Verilog/Redo Assignement/Transmitter_sim/Transmitter_sim.srcs/constrs_1/imports/UART serial communication/Basys3_Master.xdc}}]

synth_design -top top -part xc7a35tcpg236-1
write_checkpoint -noxdef top.dcp
catch { report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb }
